name: Build LaTeX document
on:
  - push
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v2
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Set outputs
        id: vars
        run: echo "::set-output name=sha_short::$(git rev-parse --short HEAD)"
      - name: Rename
        run: mv resume.pdf resume_paul_chobert_${{ steps.vars.outputs.sha_short }}.pdf
      - name: Upload PDF
        uses: actions/upload-artifact@v2
        with:
          name: resume_paul_chobert_${{ steps.vars.outputs.sha_short }}.pdf
          path: ./resume_paul_chobert_${{ steps.vars.outputs.sha_short }}.pdf
          if-no-files-found: error
